POST http://localhost:3000/login/ 
Content-Type: application/json


{
  "username": "christopher_phillips",
  "password": "christy@123"
}


###
GET  http://localhost:3000/states/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgyNjk4NjAzfQ.Xa0ZNs-mdP_rE2cLb8Xym-Phu48UtBmn-D_K722rfLA



###
GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgyNjk4NjAzfQ.Xa0ZNs-mdP_rE2cLb8Xym-Phu48UtBmn-D_K722rfLA



###
POST http://localhost:3000/districts/
Content-Type: application/json


{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###
GET http://localhost:3000/districts/332/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgyNjk4NjAzfQ.Xa0ZNs-mdP_rE2cLb8Xym-Phu48UtBmn-D_K722rfLA


###
DELETE http://localhost:3000/districts/55/ 


###
PUT http://localhost:3000/districts/3/ 
Content-Type: application/json


{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}


###
GET http://localhost:3000/states/:stateId/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgyNjk4NjAzfQ.Xa0ZNs-mdP_rE2cLb8Xym-Phu48UtBmn-D_K722rfLA

